/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\model\proffi\scene.gltf 
Author: Werstakoff (https://sketchfab.com/Werstakoff)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/proffi-216-3-3-2-995c0c7790cf49f4b272778369302ddc
Title: Верстак Верстакофф ® PROFFI-216 Д3 Д3 Э2
*/

import React, { useEffect, useState } from 'react'
import { Edges, Outlines, useCursor, useGLTF, useSelect } from '@react-three/drei'
import { useControls } from 'leva'

export default function Proffi1(props) {
  const [hovered, setHover] = useState(false)
  const selected = useSelect()
  useEffect(() => {
    console.log(selected);
  }, [selected])
  const panel = useControls("Верстак", {
    Красный: { value: 0, min: 0, max: 1, step: 0.01 },
    Зеленый: { value: 0, min: 0, max: 1, step: 0.01 },
    Синий: { value: 1, min: 0, max: 1, step: 0.01 },
    Отображать: true,
    "Запчасть_1": { value: true },
    "Запчасть_2": { value: true },
    "Запчасть_3": { value: true },
    "Запчасть_4": { value: true },
    "Запчасть_5": { value: true },
    "Запчасть_6": { value: true },
    "Запчасть_7": { value: true },
    "Запчасть_8": { value: true },
    "Запчасть_9": { value: true },
    "Запчасть_10": { value: true },
    "Запчасть_11": { value: true },
    "Запчасть_12": { value: true },
    "Запчасть_13": { value: true },
    "Запчасть_14": { value: true },
    "Запчасть_15": { value: true },
  })
  const { nodes, materials } = useGLTF('/model/proffi/scene.gltf')
  materials.pasted__aiStandardSurface2.color = {
    b: panel.Синий,
    g: panel.Зеленый,
    isColor: false,
    r: panel.Красный
  }
  materials.aiStandardSurface2.color = {
    b: panel.Синий,
    g: panel.Зеленый,
    isColor: true,
    r: panel.Красный
  }
  // console.log(materials.aiStandardSurface2)
  materials.aiStandardSurface2.blendColor = {
    b: 1,
    g: 1,
    isColor: true,
    r: 1
  }
  // console.log(materials.pasted__aiStandardSurface2);
  useCursor(hovered)
  return (
    <group {...props} dispose={null}
    
      // scale={[0.15, 0.15, 0.15]} 
      visible={panel.Отображать} castShadow receiveShadow onClick={props.onClick} onPointerOver={(e) => (e.stopPropagation(), setHover(true))}
      onPointerOut={(e) => setHover(false)} >
      <group scale={[1, 1, 1.127]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.aiStandardSurface1} position={[0.093, 0, 0]} castShadow receiveShadow visible={panel.Запчасть_1}>
        <Outlines thickness={0.1} color="hotpink" />

        </mesh>
        <mesh geometry={nodes.Object_38.geometry} material={materials.aiStandardSurface1} position={[0.093, -1.571, 0]} castShadow receiveShadow visible={panel.Запчасть_2}/>
        <mesh geometry={nodes.Object_13.geometry} material={materials.aiStandardSurface1} castShadow receiveShadow visible={panel.Запчасть_3}/>
        <mesh geometry={nodes.Object_16.geometry} material={materials.aiStandardSurface3} castShadow receiveShadow visible={panel.Запчасть_4}/>
        <mesh geometry={nodes.Object_19.geometry} material={materials.aiStandardSurface3} castShadow receiveShadow visible={panel.Запчасть_5}/>
        <mesh geometry={nodes.Object_22.geometry} material={materials.aiStandardSurface6} castShadow receiveShadow visible={panel.Запчасть_6}/>
        <mesh geometry={nodes.Object_24.geometry} material={materials.aiStandardSurface4} castShadow receiveShadow visible={panel.Запчасть_7}/>
        <mesh geometry={nodes.Object_27.geometry} material={materials.aiStandardSurface2} castShadow receiveShadow visible={panel.Запчасть_8}/>
        <mesh geometry={nodes.Object_29.geometry}
          material={materials.pasted__aiStandardSurface2}
          castShadow receiveShadow
          visible={panel.Запчасть_9}
        />
        <mesh geometry={nodes.Object_32.geometry} material={materials.aiStandardSurface3} castShadow receiveShadow visible={panel.Запчасть_10}/>
        <mesh geometry={nodes.Object_35.geometry} material={materials.aiStandardSurface3} castShadow receiveShadow visible={panel.Запчасть_11}/>
      </group>
      <mesh geometry={nodes.Object_41.geometry} material={materials.aiStandardSurface5} castShadow receiveShadow visible={panel.Запчасть_12}/>
      <mesh geometry={nodes.Object_44.geometry} material={materials.aiStandardSurface2} castShadow receiveShadow visible={panel.Запчасть_13}/>
      <mesh geometry={nodes.Object_47.geometry} material={materials.aiStandardSurface3} castShadow receiveShadow visible={panel.Запчасть_14}/>
      <mesh geometry={nodes.Object_49.geometry} material={materials.aiStandardSurface2} castShadow receiveShadow visible={panel.Запчасть_15}>
        {/* <Edges visible={selected.length>0} scale={1.1} renderOrder={1000}>
        <meshBasicMaterial transparent color="#000" depthTest={false} />
        </Edges> */}
        <Outlines thickness={0.1} color="hotpink" />
      </mesh>

        <Outlines thickness={0.1} color="hotpink" />
    </group>
  )
}

useGLTF.preload('/model/proffi/scene.gltf')
